#!/bin/bash -e

thisdir="$(cd "$(dirname "$0")" && pwd)"

source "$thisdir/ci-tools/wrappers.sh"

requirements="$build_dir/requirements-tox.txt"

pip install poetry-plugin-export==1.9.0

test -f $requirements || (
    mkdir -p "$build_dir"
    run "$thisdir/poetry" export --verbose --dev --without-hashes | \
        grep -E -o 'tox==[0-9\.]+' > "$requirements"
)

install_and_run_tool tox "-r$requirements" "$@"
